In [2]:
import numpy
n = numpy.arange(27)

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
m=numpy.asarray([[123,12,13,14],[],[]])

In [8]:
import cv2

In [10]:
im_g=cv2.imread("/home/will/projects/Udemy_python/files/smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
cv2.imwrite("/home/will/projects/Udemy_python/files/newsmallgrey.png",im_g)

True

In [14]:
a=[1,2,3]

In [15]:
a[0:2]

[1, 2]

In [18]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [20]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [21]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [25]:
ims=numpy.hstack((im_g,im_g,im_g))

In [26]:
ims


array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [27]:
lst=numpy.vsplit(ims,3)

In [28]:
lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182]], dtype=uint8)]

In [29]:
lst[0]

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143]], dtype=uint8)